### ISSUE TITLE
remove serif fonts

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/vets-who-code-app#104]
Serif fonts aren't really a good idea for a tech company. Gotta stay futuristic. Let's keep the same font everywhere while using font-weight and underlines to dictate the importance.

**Comment by TheSavageDev** [comment]
I think you can be successful with serif fonts. MDN even uses them. Sony has used them for its logo for years.

I think the more important thing is font pairing. Making sure your fonts work together. You could totally do a Serifed font for headers with sans-serif for everything else. 

Domine and Roboto always looks good together. https://www.campaignmonitor.com/resources/guides/2018-email-marketing-predictions/
