### ISSUE TITLE
Submit buttons lowercase

### ISSUE THREAD

**Issue by gixxerblade** [Vets-Who-Code/vets-who-code-app#163]
**Describe the bug**
The Submit buttons on the Mentor and Apply pages are lowercase. 

**To Reproduce**
1. Go to https://vetswhocode.io/apply
2. Scroll down to 'submit'
4. See lowercase buttons

**Expected behavior**
I expect the button to be "Submit" rather than "submit"

**Screenshots**
Not appropriate

**Desktop (please complete the following information):**
All browsers

**Smartphone (please complete the following information):**
All browsers

**Additional context**
None

**Comment by jgarcia260** [comment]
@gixxerblade 
Any feedback on this pull request?
