### ISSUE TITLE
Page headers take up too much room on page

### ISSUE THREAD

**Issue by gixxerblade** [Vets-Who-Code/vets-who-code-app#194]
**Is your feature request related to a problem? Please describe.**
Page headers currently have a viewport height of 45vh. 45vh puts the information too far down the page where the top fold should be where the user is looking for the information they're looking for. 

**Describe the solution you'd like**
Recommend 25vh's so the page header isn't the focus of the page but rather the information the user is looking for.

**Describe alternatives you've considered**
None

**Additional context**

### 45vh image

![45vh](https://i.ibb.co/qssDSK7/45vh.png)

### 25vh image

![25vh](https://i.ibb.co/nbv4hwW/25vh.png)

**Comment by thePlebDev** [comment]
if this is open I would like to help. Thank you

**Comment by andrew-t-james** [comment]
@gixxerblade Looks like this change could cause #202 to happen more often?

**Comment by gixxerblade** [comment]
Yeah. When this issue goes active we can address it then. Maybe look into just removing the breadcrumb and header and put the keep the header on the page?

**Comment by andrew-t-james** [comment]
@gixxerblade should we repurpose this issue to remove page headers so we don't have to do multiple passes to fix it?

**Comment by usmcamgrimm** [comment]
This can probably be closed. The change is active in production from a previous commit.
