### ISSUE TITLE
Fix Spelling Errors and Grammar

### ISSUE THREAD

**Issue by gixxerblade** [Vets-Who-Code/vets-who-code-app#196]
**Describe the bug**
There are a couple of spelling and grammatical errors that need to be addressed. 

**To Reproduce**
1. Go to the site
2. Click on any internal link
3. Find spelling and grammatical errors

**Expected behavior**
The site the should be free of misspelled words and grammatical mistakes

**Screenshots**
n/a

**Additional context**
none

**Comment by judyz01** [comment]
I've made a PR for this, #198 , I'm a first-time contributor so please let me know if you need anything else!
