### ISSUE TITLE
Adjust Navbar Height on Smaller Monitors

### ISSUE THREAD

**Issue by usmcamgrimm** [Vets-Who-Code/vets-who-code-app#202]
**Describe the bug**
On smaller monitors, the navbar overlaps the page headers..

**To Reproduce**
1. Resize the display to 1201px - 1400px to view.

**Expected behavior**
Adjust nav height for lower resolutions.

**Screenshots**
![image](https://user-images.githubusercontent.com/4663503/95020565-ed5b0580-0639-11eb-9a9b-fda07798f2f5.png)

**Additional context**

**Comment by gixxerblade** [comment]
#208 fixes this issue. PR waiting for review.
