### ISSUE TITLE
Mobile menu stays open when you click outside

### ISSUE THREAD

**Issue by gixxerblade** [Vets-Who-Code/vets-who-code-app#210]
## Bug
When a user clicks outside of the mobile menu it should close. Right now the only way to close the mobile menu is to either navigate to a page or click the ❌, 

## To Reproduce

1. On a mobile device visit https://vetswhocode.io/
2. Click on :hamburger: menu
3. Try and click outside of the navigation without visiting link or clicking ❌
4. See bug

## Expected behavior

Expected behavior is for the menu  to vanish when clicking outside of it.

## Smartphone (please complete the following information):**
 - Device: any mobile device
 - OS: any OS
 - Browser any mobile browser
 - Version any

**Additional context**
Probably should have been fixed in #207

**Comment by andrew-t-james** [comment]
I can take this.
