### ISSUE TITLE
Dark mode Icon dropping down to new line

### ISSUE THREAD

**Issue by andrew-t-james** [Vets-Who-Code/vets-who-code-app#213]
**Describe the bug**
When the browser width is 1024 dark mode icon is dropping down to a new line.

**To Reproduce**
1. Go to any page
2. Change browser width.

**Expected behavior**
Icon should not drop move to a new line

**Screenshots**
![image](https://user-images.githubusercontent.com/13269277/95850585-ae524180-0d16-11eb-9902-a0f2a631a579.png)

**Desktop (please complete the following information):**
 - Browser [all]

**Additional context**

**Comment by tricinel** [comment]
Hey @andrew-t-james, is this one up for grabs? :)

**Comment by gixxerblade** [comment]
@tricinel sure. Go for  it! Thanks! 👏 🔥

**Comment by tricinel** [comment]
Fantastic! Thanks :)
