### ISSUE TITLE
Keyboard Nav - Dark Mode

### ISSUE THREAD

**Issue by enmckinn** [Vets-Who-Code/vets-who-code-app#240]
**Describe the bug**
If you are using the keyboard to navigate the site on a chrome browser, dark mode won't toggle using the enter key as all other links function.

**To Reproduce**
1. In Chrome browser, tab until the focus is on the dark mode toggle.
2. Hit enter.
3. Mode does not toggle.

**Expected behavior**
Pressing the enter key should cause the modes to toggle just as the mouse click does.

**Additional context**

**Comment by gixxerblade** [comment]
WRT that issue for the dark mode not being accessible according to WIA ARIA: Note that supporting SPACE in addition to ENTER is not required by WCAG 2.0; this control would still be keyboard accessible without the key event handler for SPACE. However, supporting platform keyboard conventions for controls is strongly encouraged.

It already supports the spacebar

Here's the reference

https://www.w3.org/WAI/GL/wiki/Making_actions_keyboard_accessible_by_using_keyboard_event_handlers_with_WAI-ARIA_controls
