### ISSUE TITLE
Apply Page - Required Pre-work

### ISSUE THREAD

**Issue by enmckinn** [Vets-Who-Code/vets-who-code-app#242]
**Is your feature request related to a problem? Please describe.**
I would like to see a button on the Apply page that directs visitors to the pre-work.  It would be more clear at a glance that you can easily navigate to that documentation, especially helpful for people who skim the text.

**Describe the solution you'd like**
A button above the application form 

**Additional context**
![Artboard 1](https://user-images.githubusercontent.com/16172315/99203329-309fac80-2780-11eb-9ec1-003e73359a67.png)

**Comment by gixxerblade** [comment]
closed by #243
