### ISSUE TITLE
Add dark and light Netlify svg logo to the sponsor slider

### ISSUE THREAD

**Issue by gixxerblade** [Vets-Who-Code/vets-who-code-app#244]
Netlify is a sponsor of VWC and should be displayed on the sponsor slider

**Describe the solution you'd like**
Using the dark and light svg logos here: https://www.netlify.com/press/ add them to the sponsor slider

**Describe alternatives you've considered**
None.

**Additional context**
None

**Comment by J3ffJessie** [comment]
Which logo are we looking for? 

- Full Logo
- Simple Logo
- Logomark

More context of which one we prefer for the sponsor slide would be helpful for which logo we want.

**Comment by andrew-t-james** [comment]
@J3ffJessie looks like this work was captured in the most recent merge but the issue was not closed out. @gixxerblade can you clarify if I missed something here?
