### ISSUE TITLE
Frequently Asked Questions Page

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/vets-who-code-app#251]
I get a lot of emails asking the same three or four questions. Takes a lot of my time away from doing more important things.

**Describe the solution you'd like**
I would like it if we had a Frequently Asked Questions page.

**Describe alternatives you've considered**
The alternatives is answering emails. I hate email.

**Comment by Olaleye-Blessing** [comment]
Can I work on this?
Where should FAQ link be?
What're the questions and answers to be displayed?
