### ISSUE TITLE
Contact form in the footer 

### ISSUE THREAD

**Issue by dtetreau251** [Vets-Who-Code/vets-who-code-app#259]
During the VetsWhoCode [javascript-job-search-mvp]( https://github.com/Vets-Who-Code/march2021/tree/main/javascript-job-search-mvp) project, the march2021 cohort members made a contact form in the footer. Per Jerome's request, this is being made into an issue in this repo. It is requested that this feature is added to the vets-who-code-app.

The contact form should be added above the "Made with  By #VetsWhoCode" text in the main app. There is an example below:

![footer](https://user-images.githubusercontent.com/57218090/115638102-556ff100-a2d7-11eb-875c-50044df29d8f.PNG)

**Comment by Cameron-Porter** [comment]
@dtetreau251 this was put up almost a year ago, if it is still a want then I'll give it a shot.

**Comment by jeromehardaway** [comment]
> @jeromehardaway @dtetreau251 this was put up almost a year ago, if it is still a want then I'll give it a shot.

@Cameron-Porter go for it.

**Comment by Cameron-Porter** [comment]
Merged
