### ISSUE TITLE
Add CoC

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/vets-who-code-app#269]
As an organization, we need to focus on showcasing that can we push forward the conversation that veterans are not a monolith and that we are still here to make the world a better place, whether it's in uniform or behind a keyboard.

A part of this is to state explicitly who we are and what is expected of us and each other.  To do that, we need a code of conduct posted with ease to find before a person joins  #VetsWhoCode.

**Comment by gixxerblade** [comment]
Is there a CoC design?
