### ISSUE TITLE
Add Podcast link to sitemap

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/vets-who-code-app#287]
Great first issue for a person in Hacktoberfest. Add a podcast link to the sitemap.

**Comment by Foo-Maker** [comment]
Hey.
I woud give a try.

**Comment by stephanlamoureux** [comment]
We have this as part of our PR #278, the whole nav was tightened up. 

![nav](https://user-images.githubusercontent.com/16889593/135893522-83275b0b-ecd6-4810-a10b-1ccc1fded46a.png)

**Comment by jeromehardaway** [comment]
@stephanlamoureux this is a small ticket though. I don't wait for something that is in prod now. Besides, Sitemap is SEO issue as of right now.
