### ISSUE TITLE
Buttons not full width in accordion panels

### ISSUE THREAD

**Issue by andrew-t-james** [Vets-Who-Code/vets-who-code-app#313]
**Describe the bug**

**To Reproduce**
1. Go to Mentor or Syllabus pages and open any accordion panel.
2. Button is not full width.
3. I suspect a global CSS change is the root cause of this issue.

**Expected behavior**
The button should be full width on accordion panels 
Current
![image](https://user-images.githubusercontent.com/13269277/141122069-e27ed34f-9e6a-4564-b788-c5c2f71ca314.png)
![image](https://user-images.githubusercontent.com/13269277/141122439-326f508f-5161-4719-ba99-34a2ecb9e1cb.png)
Expected
![image](https://user-images.githubusercontent.com/13269277/141122691-2f2d404f-be09-42bd-bd26-a9e38bd3b253.png)

**Comment by NguyenLyy** [comment]
Can I help you????
