### ISSUE TITLE
Update Text

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/vets-who-code-app#332]
Update text for the cohort.

Text was leftover from last time Next was built, so we have to change it.

change from: Launching something new on Veteran's Day. Be sure to apply!

To: Sign Up For Our Next Cohort.

**Comment by aiethics95** [comment]
Hey, I can take a look at the code and try to fix it! I commented the following comment on one of your other issues for this project that applies to this as well: I am a bit new to doing this on github, can you please let me know where I can find this code? Thanks (:

**Comment by RubenLeerentveld** [comment]
Edited the text and created a pull request for this issue!
UPDATED TEXTINDEX.JS#339
