### ISSUE TITLE
Add Space between stars and text on " RETOOLRETRAINRELAUNCH"

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/vets-who-code-app#334]
**Describe the bug**
Stars and Text for RETOOLRETRAINRELAUNCH are very close together. Needs to be fixed.

**To Reproduce**
Go to main page and scroll to " RETOOLRETRAINRELAUNCH"

**Comment by phershbe** [comment]
Hello Jerome, cool project! I'm newer to open source and would love to work on this. I'm not a veteran, but I love this cause, does that matter?

I had some problems getting the localhost to work, "git clone git@github.com:Vets-Who-Code/vwc-site.git" gave me an error immediately and I tried "git clone https://github.com/Vets-Who-Code/vets-who-code-app.git" and got through nvm install and npm install but got an error when I went to the localhost. I wasn't super confident opening an issue in case it's something stupid, but if necessary I certainly could.

**Comment by jeromehardaway** [comment]
It's only open to our community.

**Comment by jeromehardaway** [comment]
> Hello Jerome, cool project! I'm newer to open source and would love to work on this. I'm not a veteran, but I love this cause, does that matter?
> 
> 
> 
> I had some problems getting the localhost to work, "git clone git@github.com:Vets-Who-Code/vwc-site.git" gave me an error immediately and I tried "git clone https://github.com/Vets-Who-Code/vets-who-code-app.git" and got through nvm install and npm install but got an error when I went to the localhost. I wasn't super confident opening an issue in case it's something stupid, but if necessary I certainly could.

It's only open to our community.

**Comment by phershbe** [comment]
Oh okay, sorry about that. Cool project anyway!
