### ISSUE TITLE
Fix second Donate Button

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/vets-who-code-app#336]
**Describe the bug**
Second Donate Button Is essentially a link. Need to fix.

**To Reproduce**
Go to the second donate button.
See that it is a link.

**Expected behavior**
Should be a button.

**Comment by aiethics95** [comment]
Hey, I can take a look at the code and try to fix it! Also I am a bit new to doing this one github, can you please let me know where I can find this code? Thank you!

**Comment by jeromehardaway** [comment]
Completed in class

**Comment by jeromehardaway** [comment]
Closed in class
