### ISSUE TITLE
Favicon is missing

### ISSUE THREAD

**Issue by axecopfire** [Vets-Who-Code/vets-who-code-app#376]
**Describe the bug**
No Favicon
![image](https://user-images.githubusercontent.com/24581531/162589427-dcf45463-9405-48bb-aeac-0004e5d2e83e.png)

**To Reproduce**
1. Go to vetswhocode.io

**Expected behavior**
I'd expect a Favicon on the tab

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by Cameron-Porter** [comment]
Completed by @usmcamgrimm
