### ISSUE TITLE
Add a Open Graph and Twitter card image (and supporting meta tag items)

### ISSUE THREAD

**Issue by ayumi-b** [Vets-Who-Code/vets-who-code-app#382]
**Describe the bug**
When a user posts a VWC website link on any social media, a gray box appears for a preview image, instead of a nice image and short description.

https://ogp.me/
https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards

**Why it's important**
It definitely adds better engagement value when our website is posted by anyone.  
https://ahrefs.com/blog/open-graph-meta-tags/

**Expected behavior**
Use something like these to test the final look:
https://cards-dev.twitter.com/validator
https://www.opengraph.xyz/

**Additional Support**
Please contact me if you'd like any support in creating a good VWC metatag image.

**Comment by Cameron-Porter** [comment]
@ayumi-b I tested an image on the opengraph site and it only populated for discord. Is that normal? I've never used that site before, so wanted to check before pushing a PR.

**Comment by ayumi-b** [comment]
@Cameron-Porter what looks like is happening is that they've all been able to have that preview text, and Discord's the only that looks right, because Discord doesn't show images anyway.  What you're missing on the others is the image. 

These are still blank, so filling this out should yield a different result.

<meta property="og:image" content="">
<meta name="twitter:image" content="">
