### ISSUE TITLE
Links in donate page are not working.

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/vets-who-code-app#386]
**Describe the bug**
The links in the body on the donate page are inoperable.

**To Reproduce**
1. Go to donate page.
2. Click on urls.

**Expected behavior**
You go to the link.

**Desktop (please complete the following information):**
 - OS:  MacOS
 - Chrome
 - Version 100.0.4896.127 (Official Build) (x86_64)

**Comment by Takomane** [comment]
Good morning!

I just attempted to recreate the issue and could only find the Blog, Podcast, and link when you click on hello@vetswhocode to 404. Are these the only links you found inoperable as well?

Thank you!

**Comment by jeromehardaway** [comment]
> Good morning!
> 
> I just attempted to recreate the issue and could only find the Blog, Podcast, and link when you click on hello@vetswhocode to 404. Are these the only links you found inoperable as well?
> 
> Thank you!

@Takomane the links in the body of the donate page do not work. Everything else you responded to is behind an API wall because its powered by contentful. The Benevity, Brightfunds, etc do not work.

**Comment by Takomane** [comment]
Something must be wrong on my end, I cannot recreate the bug. When I click the links they go to the Benevity, Brightfund, and other pages. Is it supposed to open a new tab rather than the same tab, or is it going to the wrong site?
