### ISSUE TITLE
Ensure Font is Uniform Across Pages

### ISSUE THREAD

**Issue by Cameron-Porter** [Vets-Who-Code/vets-who-code-app#407]
**Describe the bug**
Ensure font is uniformly applied to the app. It seems it is not fully covering the Apply -> Mentor page.

**To Reproduce**
1. Go to Apply
2. Click on Mentor
3. Scroll down to view different fonts displayed on the page

**Expected behavior**
Expect the Gotham font to be applied to as per other pages in the app.

**Comment by Takomane** [comment]
I may be misreading, or need new glasses, but each individual class Inherits from body. When I inspect the page and look at each element the styles has:

body, h1, h2, h3, h4, h5, h6 {
    font-family: Gotham,sans-serif;
}

**Comment by stephanlamoureux** [comment]
@Takomane It does show that, but it's not displaying as such. I had to change the typed.js font by using inline styling.

```
<Typed
                    style={{ fontFamily: 'Gotham, sans-serif' }}
                    className="typedString"
                    strings={[
                      'RESULTS DRIVEN',
                      '100% ONLINE',
                      'LEARN PRAGMATICALLY',
                      'PREPARED FOR THE INDUSTRY',
                    ]}
                    typeSpeed={70}
                    backSpeed={80}
                    smartBackspace
                    loop
                  />
```
You can see here that in the podcast headers it's not using the Gotham font. I can't remember, but I think if you have Gotham installed locally it works everywhere as intended so it's not noticeable to everyone.

![font](https://user-images.githubusercontent.com/16889593/177054685-3855414d-efd6-432d-bebd-9d5bfa92bfed.jpg)
