### ISSUE TITLE
<Romeo-Golf-Main Branch> Test Resume Landing Page

### ISSUE THREAD

**Issue by Cameron-Porter** [Vets-Who-Code/vets-who-code-app#438]
# Description

As a developer, I want to ensure the resume landing page looks as it should and the button takes users to the next component.

### Acceptance Criteria

- [ ] Create a snapshot test for the resume landing page
- [ ] Create functional test to ensure the button to the next component works as it should.

### Business Sense

- These tests ensure that the resume landing page remains consistent and there are no breaking changes visually. It also proves the functionality of the button works which is what allows users the opportunity to try our product.

**Comment by Manavpreeet** [comment]
I would like to work on it
