### ISSUE TITLE
Roadmap link broken in README.md

### ISSUE THREAD

**Issue by tr-ace** [Vets-Who-Code/vets-who-code-app#474]
**Describe the bug**
Noticed the link to the roadmap.md file was broken when trying to access it from the README.md file.

**To Reproduce**
1. Go to README.md
2. Click on the `roadmap` hyperlink
3. Notice it gives a 404 error

**Expected behavior**
Expected to be taken to the roadmap.md file.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome
 - Version [115]

**Additional context**
I'm currently submitting a PR to fix this issue.

**Comment by jeromehardaway** [comment]
Hi,
Since most of the things on the current roadmap are done and we are pushing the new web app within the week, I'm closing this. However we will put a new projects board roadmap up in the coming weeks so watch this space.
