### ISSUE TITLE
Donor Link Missing in Mobile Menu of Next.js & Tailwind App

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/vets-who-code-app#483]
### Description: 
We have identified an issue with our mobile navigation menu. Specifically, the link leading to the donor page needs to be included. This absence inhibits our mobile users' ability to quickly and conveniently navigate to the donor page, potentially impacting the user experience and donor conversion rates.

### Steps to reproduce:
1. Open our application in any mobile browser (please specify if the issue is limited to a particular browser).
2. Click on the menu icon to expand the navigation menu.
3. Scroll through the available options.

### Expected Behavior:
The donor page link should be present and correctly listed among the other navigation options in the mobile menu. On clicking this link, users should be redirected to the donor page.

### Actual Behavior:
The donor link needs to be present in the mobile menu, making it difficult for users to navigate to the donor page from the menu.

### Frequency:
This issue occurs every time the mobile menu is accessed.

### Severity:
The severity of this issue is high due to its potential impact on user experience and donor conversion rates.

### Environment/Platform:
- Device: Mobile
- OS: All Mobile Operating Systems
- Browser: All Browsers

**Comment by JVSONV** [comment]
I'm not seeing the Donor page even on Desktop. I'd like to also point out that there seems to be either a placeholder or broken image as the background of the mobile nav. 

![Screenshot 2023-08-10 at 6 06 41 PM](https://github.com/Vets-Who-Code/vets-who-code-app/assets/112579344/dd923391-99f5-40cf-a979-41e14c994ad1)
