### ISSUE TITLE
Add Playwright to web app

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/vets-who-code-app#491]
**Description:**
To enhance the quality and efficiency of our web app testing process, we need to integrate Playwright, a powerful end-to-end testing library, into our existing codebase. Playwright will allow us to automate the testing of various user interactions and scenarios, ensuring a robust and reliable application.

Please let me know if you need any adjustments or additional details added to the ticket description.

**Comment by colburncodes** [comment]
I would like to work on this. @jeromehardaway

**Comment by jeromehardaway** [comment]
@colburncodes i implemented playwright already, but you could write tests for the forms. Start there.

**Comment by colburncodes** [comment]
@jeromehardaway Great, Thanks! I will start testing the forms.
