### ISSUE TITLE
Change URL for troop application to /apply

### ISSUE THREAD

**Issue by ayumi-b** [Vets-Who-Code/vets-who-code-app#501]
The URL for the applications in the previous webapp version was vetswhocode.io/apply.  It's now under /apply-to-be-a-student 

The /apply url is simply an easier one to share. Also, we have multiple previous social mentions pointing to /apply for those who want to apply.  The consistency would help so that the /apply won't go to 404-----or one solution is to redirect the /apply to the new page to apply. Though the mentor link is below the 'apply' nav, the url for that page is /become-a-mentor, so the /apply page wouldn't compete with the mentor application.  (the mentor one could be shortened to /mentor)

**Comment by jeromehardaway** [comment]
PR is out there. Check and review.

**Comment by jeromehardaway** [comment]
Done.
