### ISSUE TITLE
Broken Link to Contribution Guidelines

### ISSUE THREAD

**Issue by niksseif** [Vets-Who-Code/vets-who-code-app#520]
Hi there,

While attempting to access the [contribution guidelines](https://github.com/Vets-Who-Code/vets-who-code-app/blob/master/.github/contributing.md), I found that the link is currently broken and returns a 404 error. It would be great if this could be addressed so that potential contributors can easily access the guidelines from the ReadMe.

Thank you!

**Comment by jeromehardaway** [comment]
Hi there,

Thank you for pointing this out to us! I'm pleased to inform you that the issue with the broken link has been resolved. You should now be able to access the contribution guidelines directly from the ReadMe without any issues. We truly appreciate your vigilance and patience. Your feedback helps us make the Vets Who Code web app better for everyone.

Warm regards,
Jerome
