### ISSUE TITLE
"View All Modules" leads to nowhere

### ISSUE THREAD

**Issue by ayumi-b** [Vets-Who-Code/vets-who-code-app#535]
**The Issue**
Currently on the front page, the "View All Modules" button below the Our Modules section goes to 404. 

**Replicating the Issue**
Go to the home page https://vetswhocode.io/ scroll down to "Our Modules" and press "View All Modules" button.  It currently goes to 404

**Solution**
Basic solution would be to link the button to https://vetswhocode.io/curriculum/subjects

Enhanced solution would be to add a good explainer to that page about the modules so that it's not a page of buttons (which is currently the case)

**Comment by jeromehardaway** [comment]
Completed issue.
