### ISSUE TITLE
Add EIN to the website footer

### ISSUE THREAD

**Issue by ayumi-b** [Vets-Who-Code/vets-who-code-app#542]
**Problem:**
The website currently does not show the nonprofit EIN on the website

**Solution:**
At the footer, place the following statement about the copyright info, perhaps centered to the website or near the Candid image.  It just needs to look good at all sizes!

Vets Who Code is a registered 501(c)(3) nonprofit under EIN 86-2122804. Donations are tax-deductible to the fullest extent allowable under the law.

**Comment by jeromehardaway** [comment]
Completed by @IngridFuentes
