### ISSUE TITLE
Subscribe Hover state

### ISSUE THREAD

**Issue by andrew-t-james** [Vets-Who-Code/vets-who-code-app#62]
**Describe the bug**
Hover state specifically for the subscribe button on the landing page is broken. Needs a hover state where font color remains white.

**To Reproduce**
1. Go to index page
2.  Scroll to the bottom of page
3. Hover subscribe button

**Screenshots**
![sub](https://user-images.githubusercontent.com/13269277/51511155-b7261580-1dc5-11e9-93ef-340e128f4b15.gif)

**Comment by andrew-t-james** [comment]
@ozzievee if you're up for it.

**Comment by ozzievee** [comment]
I'm up for it
