### ISSUE TITLE
Modal for donate does not have a close button

### ISSUE THREAD

**Issue by andrew-t-james** [Vets-Who-Code/vets-who-code-app#71]
**Describe the bug**
There is no close button on the modal. Spacing in the modal needs to be fixed as well. The information is all left aligned. Can we center or rearrange content to flow better?

**To Reproduce**
1. Go to https://vetswhocode.io/donate/
2. Scroll to the bottom of page.
3. Click on click on donate button modal will appear.

**Expected behavior**
Expected behavior the ability to close the modal from a button within the modal. 

**Screenshots**

![image](https://user-images.githubusercontent.com/13269277/53064216-a633f700-348c-11e9-947e-e43ccd69dee7.png)

**Comment by ozzievee** [comment]
I am on it!
