### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/vets-who-code-app#90]
Lets focus on adding Dark mode to VWC

**Comment by axecopfire** [comment]
Was looking at this. Is there already work being done on this?

**Comment by andrew-t-james** [comment]
@axecopfire nope, not currently.

**Comment by marklocklear** [comment]
@axecopfire I'm willing to tag team with you on this if you can take the lead.

**Comment by axecopfire** [comment]
Made a working prototype. I was wondering if I could get some help on how these tests work and how I should going about updating them.

**Comment by andrew-t-james** [comment]
@axecopfire what branch so I can take a look?

**Comment by jeromehardaway** [comment]
I got this one. I can use this in conjunction with another ticket I am making for cleaning up the css.

**Comment by gixxerblade** [comment]
Ticket here; https://vets-who-code.atlassian.net/browse/PROD-8?atlOrigin=eyJpIjoiMTEyZTQ4NDBkMzZhNDY0YWI5YmVkMmZiMjk5YTRiZjAiLCJwIjoiaiJ9

TODO: 

- Add fallback for browsers that don't support css variables.
-Add fallback for users with JS turned off.
- Input box colors need to change.
- Partner icons: need svgs.
