### ISSUE TITLE
Add Stripe Shop

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/vets-who-code-app#91]
As a Executive Director, I want The Hashflag Swag Shop to be Native to the web app. I want to use the Stripe Checkout API as well As Gatsby.

**Comment by gixxerblade** [comment]
Is there already a Stripe account associated with the HashFlag Swag Shop? For shipping is it going to be a flat rate or calculated at checkout? What about taxes?

**Comment by jeromehardaway** [comment]
@gixxerblade Its using Shopify, I think this was made before the app was live. I would check to see if there is a plugin where we can integrate that stuff.
