### ISSUE TITLE
fix slider color ratio

### ISSUE THREAD

**Issue by jeromehardaway** [Vets-Who-Code/vets-who-code-app#94]
color ratio is off on the slider, making text harder to see.  Maybe we need to choose another image?

**Comment by andrew-t-james** [comment]
@jeromehardaway this work is partially completed on a branch that is waiting to be merged. I need assets for Carla to be able to replace Andrew. I also need whichever image you'd like to replace the above mentioned in this issue.

**Comment by jeromehardaway** [comment]
@andrew-t-james I am pinging Carla now and Schuster has the new image.

**Comment by jeromehardaway** [comment]
Fixed
